apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: words-db
  namespace: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: tcp
  selector:
    app: words-db
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db
  labels:
    app: words-db
  namespace: database
spec:
  template:
    metadata:
      labels:
        app: words-db
    spec:
      containers:
      - name: db
        image: dockersamples/k8s-wordsmith-db
        ports:
        - containerPort: 5432
          name: db
