apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: words-web
  namespace: web
spec:
  ports:
    - port: 8081
      targetPort: 80
      name: http
  selector:
    app: words-web
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
    app: words-web
  namespace: web
spec:
  template:
    metadata:
      labels:
        app: words-web
    spec:
      containers:
      - name: web
        image: quinont/web:3
        ports:
        - containerPort: 80
          name: words-web
