apiVersion: v1
kind: Service
metadata:
  name: words
  namespace: api
  labels:
    app: words
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: words    
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: words
  namespace: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: words
        version: v1
    spec:
      containers:
      - name: words
        image: quinont/words:1
        ports:
        - containerPort: 8080
          name: api

