apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: app2
  labels:
    app: app2
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: app2
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app2
  namespace: app2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app2
        version: v1
    spec:
      containers:
      - name: app2
        image: quinont/app2:1
        ports:
        - containerPort: 5000
          name: app2

